version: '3'

services:
  model:
    build: .
    restart: always
    ports:
      - '8180:8180'
    environment:
      - MODEL=/app/models/model.dill
      - PORT=8180
    volumes:
      - './models:/app/models'

